on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push (latest-stable) for master
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/snippet-service:latest-stable
          secrets: |
            gpr_user=${{ github.actor }}
            gpr_token=${{ secrets.GHCR_PAT }}

      - name: Build and push (latest-stable) for dev
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/snippet-service:latest-dev
          secrets: |
            gpr_user=${{ github.actor }}
            gpr_token=${{ secrets.GHCR_PAT }}