on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push (latest-stable) for master
        if: github.ref == 'refs/heads/master'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/snippet-service:latest-stable .
          docker push ghcr.io/${{ github.repository_owner }}/snippet-service:latest-stable

      - name: Build and push (latest-stable) for dev
        if: github.ref == 'refs/heads/dev'
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/snippet-service:latest-dev .
          docker push ghcr.io/${{ github.repository_owner }}/snippet-service:latest-dev