name: Run Script on Azure VM

on:
  push:  
    branches:
      - master

jobs:
  update-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_STABLE }}

      - name: Run Script on Azure VM
        run: |
          ssh -v -o StrictHostKeyChecking=no sonpipe@${{ secrets.VM_STABLE_IP }} << 'ENDSSH'
          cd micro-infra
          bash update-stable.sh
          ENDSSH


